version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "TheDropX"
      - "Timeraa"
    commit-message:
      prefix: "ðŸ”¼"
      prefix-development: "ðŸ”¼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "TheDropX"
      - "Timeraa"
    commit-message:
      prefix: "ðŸ”¼"
      prefix-development: "ðŸ”¼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
