blank_issues_enabled: false
contact_links:
  - name: Official Discord Server
    url: https://discord.premid.app
    about: If you are experiencing issues with your PreMiD, go to our support in our Discord server.
