name: SA
on:
  pull_request:
    branches:
      - master
jobs:
  review:
    name: Diff review
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.AUTOMERGE }}
          level: error
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
          eslint_flags: ". --ext .ts"
  analysis:
    needs: review
    name: Files check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.AUTOMERGE }}
          level: error
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: true
          eslint_flags: ". --ext .ts"