name: SV
on:
  push:
    branches:
      - master
    paths:
      - "**/metadata.json"
  pull_request:
    branches:
      - master
    paths:
      - "**/metadata.json"
jobs:
  validate:
    name: Schema Validation Check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Prep SV
        run: |
          yarn
          yarn sv:compile
      - name: Find Changed Files (direct push)
        if: github.event_name == 'push'
        run: |
          git config core.quotepath off # fixes escape sequence issue
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --output file_changes.txt
      - name: Find Changed Files (pull request)
        if: github.event_name == 'pull_request'
        uses: PreMiD/changed-files@v3
        id: changed_files
      - name: Write Changed Files (pull request)
        if: github.event_name == 'pull_request'
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: file_changes.txt
          contents: |
            ${{ steps.changed_files.outputs.files_created }}
            ${{ steps.changed_files.outputs.files_updated }}
      - name: Start SV
        run: yarn sv --colors
